ignores:
  - dist

overrides:
  - files:
      - '**/*.{js,jsx}'
    languageOptions:
      ecmaVersion: 2020
      globals: 
        browser: true
      parserOptions:
        ecmaVersion: latest
        ecmaFeatures:
          jsx: true
        sourceType: module
    settings:
      react:
        version: '18.3'
    plugins:
      - react
      - react-hooks
      - react-refresh
    rules:
      react/jsx-no-target-blank: off
      react-refresh/only-export-components:
        - warn
        - allowConstantExport: true
      react/prop-types: off

extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - eslint:recommended
