ignores:
  - dist

overrides:
  - files:
      - '**/*.{js,jsx}'
    languageOptions:
      ecmaVersion: 2020
      globals:
        browser: true
      parserOptions:
        ecmaVersion: latest
        ecmaFeatures:
          jsx: true
        sourceType: module
    settings:
      react:
        version: '18.3'
    plugins:
      - react
      - react-hooks
      - react-refresh
    rules:
      react/jsx-no-target-blank: off
      react-refresh/only-export-components:
        - warn
        - allowConstantExport: true
      react/prop-types: off

  - files:
      - src/icons/pageNotFound.jsx
      - src/icons/sendButton.jsx
    rules:
      react/jsx-props-no-spreading: off

  - files:
      - src/slices/*.js
    rules:
      no-param-reassign: off

  - files:
      - vite.config.js
    rules:
      import/no-extraneous-dependencies: off
